name = "styledbypeyt"    # your project name here

compatibility_date = "2024-10-10"

compatibility_flags = [
  "nodejs_compat",
  "nodejs_compat_fetch",
  "fetch_director_stream"
]

pages_build_output_dir = "."