name = "styledbypeyt"  # your project name, can be anything
main = "functions"     # folder where your functions live
compatibility_date = "2024-10-10"

compatibility_flags = [
  "nodejs_compat",
  "nodejs_compat_fetch",
  "fetch_director_stream"
]

# This tells Pages where your static build output is
pages_build_output_dir = "."  # or wherever your static files are built/copied

[build]
command = "npm run build"  # or whatever your build command is; can be empty or omitted if none
